### ISSUE TITLE
Contamination percent calculation

### ISSUE THREAD

**Issue by aelbehery** [KIT-IBG-5/mdmcleaner#34]
Dear John,

I have a question about contamination percent calculation. I saw in your NAR article a comparison between bin contamination calculated by checkm vs that calculated by mdmcleaner, but when I used mdmcleaner clean command, I couldn't find the contamination % value. May I know where I can find it? Or if it's not available, how I can calculate it?

I really appreciate your help and cooperation.

Best regards,

Ali

**Comment by jvollme** [comment]
answered in #33
