### ISSUE TITLE
ERROR: evaluation result not accounted for: 'silva_conflict'

### ISSUE THREAD

**Issue by chassenr** [KIT-IBG-5/mdmcleaner#37]
Hi,

I am testing MDMcleaner (version 0.8.3 installed via conda) on a set of bins, and I receive the following error:

```
-->evaluating contigs and setting filter-flags
         finished 60%. Currently analysing apparent reference database ambiguity
THERE WAS A EXCEPTION WHILE HANDLING ../bins_IOWseq000005_pre_anvio/Co_bin.92.orig.fa


ERROR: evaluation result not accounted for: 'silva_conflict'

Traceback (most recent call last):
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.3/lib/python3.10/site-packages/mdmcleaner/clean.py", line 197, in main
    db_suspects = bindata.evaluate_and_flag_all_contigs(db=db, protblasts=protblasts, nucblasts=nucblasts, db_suspects=db_suspects, fast_run=args.fast_run)
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.3/lib/python3.10/site-packages/mdmcleaner/getmarkers.py", line 1194, in evaluate_and_flag_all_contigs
    is_potential_refdb_contam = step2()
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.3/lib/python3.10/site-packages/mdmcleaner/getmarkers.py", line 1164, in step2
    if db_suspects.last_checked_evaluations() == "OK":
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.3/lib/python3.10/site-packages/mdmcleaner/review_refdbcontams.py", line 271, in last_checked_evaluations
    assert le == "OK", "\nERROR: evaluation result not accounted for: '{}'\n".format(le)
AssertionError:
ERROR: evaluation result not accounted for: 'silva_conflict'
```

In total, I had 144 bins and this error was thrown for 2 of them. Do you have any suggestions of how to solve this error?

Thanks!

Cheers,
Christiane

**Comment by jvollme** [comment]
hi, i will try to look into it. would you mind sending me the fastas of the bins that produced errors?

**Comment by jvollme** [comment]
in this particular case, there is a bug in the vurrent mdmcleaner version that raises an error if GTDB and silva taxonomies for the same marker gene directly contradict each other (default bhaviour should be to simply prefer gtdb over silva in such cases). I will try to fix it as soon as possible. as a temporary workaround you could run``` mdmcleader clean``` with the ```--fast_run``` argument (for these bins only). 

but considering your other problem it would really be helpful to have the fastas. Also maybe you could send me the fastas.
also could you perhaps also send me the ```new_blacklist_additions.tsv``` and ```overview_refdb_ambiguities.tsv``` files produced during your original run?

**Comment by chassenr** [comment]
Just FYI, I sent you the specified files via email.

**Comment by chassenr** [comment]
I am closing this issue because the error did not persist in the latest version of mdmcleaner. Thanks a lot for looking into this and sorry for my very delayed response.
