### ISSUE TITLE
TypeError in clean.py prevent MDMcleaner to exit gracefully when no blast jobs should be run

### ISSUE THREAD

**Issue by cpauvert** [KIT-IBG-5/mdmcleaner#40]
Hi @jvollme

Thanks for this tool! I ran into a small bug when running MDMcleaner (`v0.8.3` from conda). It failed with the following error message.

```python
reference-database contaminations detected during this run: 2
blasting 0 entries with blastx against reference proteins (another 1 entries were too long to blastx efficiently
Traceback (most recent call last):
  File "/home/cpauvert/projects/.snakemake/conda/a0a4db55baa73e1a514e9cd116469487/bin/mdmcleaner", line 10, in <module>
    sys.exit(main())
  File "/home/cpauvert/projects/.snakemake/conda/a0a4db55baa73e1a514e9cd116469487/lib/python3.10/site-packages/mdmcleaner/mdmcleaner.py", line 217, in main
    blacklist_additions = clean.main(args, configs)
  File "/home/cpauvert/projects/.snakemake/conda/a0a4db55baa73e1a514e9cd116469487/lib/python3.10/site-packages/mdmcleaner/clean.py", line 230, in main
    if "contamination" in db_suspects.collective_diamondblast():
TypeError: argument of type 'NoneType' is not iterable
```

By tracking it down, it seems that the culprit line is in [`review_refdbcontams.py L305`](https://github.com/KIT-IBG-5/mdmcleaner/blob/ec3b23d675caafeb94bf60ae2b09aae15e9850aa/mdmcleaner/review_refdbcontams.py#L305). I have no blast jobs to be run (`blasting 0 entries`) but so the default return value of the `collective_diamondblast()` function is  a `None`.
https://github.com/KIT-IBG-5/mdmcleaner/blob/ec3b23d675caafeb94bf60ae2b09aae15e9850aa/mdmcleaner/review_refdbcontams.py#L302-L305

But `None` is not iterable so  it makes the test in `clean.py` line 230 fail:

https://github.com/KIT-IBG-5/mdmcleaner/blob/ec3b23d675caafeb94bf60ae2b09aae15e9850aa/mdmcleaner/clean.py#L229-L233

I think that amending the `return` to `return [None]` in [L305](https://github.com/KIT-IBG-5/mdmcleaner/blob/ec3b23d675caafeb94bf60ae2b09aae15e9850aa/mdmcleaner/review_refdbcontams.py#L305) should do the trick, by keeping an iterable:

```python
foo=None
print('yes' if 'A' in foo else 'no')
# yields TypeError: argument of type 'NoneType' is not iterable
# BUT 
foo=[None]
print('yes' if 'A' in foo else 'no')
# yields no correctly
```
Do you have any test to check that it is not breaking anything?
Let me know if you prefer a pull request or do the fix yourself
Best,
Charlie

**Comment by did10** [comment]
Hi, thanks for digging in to the Problem and providing a Fix! 
I will look into it and test your fix on behalf of John.
Best, 
Mathias

**Comment by jvollme** [comment]
hi , thanks. THis is caused by a feature that i did not fully implement yet. I added a temporary fix that is easy for me to remember/notice for when i finally finish that feature...
