### ISSUE TITLE
Potential unintended behavior while directory checking and creating

### ISSUE THREAD

**Issue by did10** [KIT-IBG-5/mdmcleaner#42]
I think the implemented if condition ( line 993 ) results in unintended behavior.

https://github.com/KIT-IBG-5/mdmcleaner/blob/ec3b23d675caafeb94bf60ae2b09aae15e9850aa/mdmcleaner/read_gtdb_taxonomy.py#L991-L1000

It checks if targetdir exists and is a dir. If that's true the function returns (after the access check). If  `os.path.isdir(targetdir)` returns false (the file exists but is not a dir) the else case is executed and the function tries to create the dir which is a file.

This should raise an `OSError` in `os.makedirs(targetdir)` which is not caught. The user should sees the native error.
At the moment I sadly can't test if the resulting error message is user-friendly or not, so I'm not totally sure about this.

But if you want I can look into it.

**Comment by jvollme** [comment]
you are right. There should be a different exception with a different error message.
If you can, please do. Just make a seperate pull request for that.

**Comment by did10** [comment]
Sorry, this isn't closed. I referenced the wrong Tiket in in #45. It should have been ticket #43 not #42. In the future I will reference the ticket ID in my branch names so this should not happen again.
