### ISSUE TITLE
inconsistency in cleaner logs 

### ISSUE THREAD

**Issue by did10** [KIT-IBG-5/mdmcleaner#46]
The log message of scanning for tRNAs prints the wrong number of  universally required types of tRNA. 
The automated code says there are 21tRNAs, the hand written message says there are 20. 

![grafik](https://user-images.githubusercontent.com/26488423/195427133-9748699b-299e-4ba3-a9c5-18ce8725b932.png)

Just a small inconsistency in logger output.

**Comment by jvollme** [comment]
that is not really an inconsistency, although it may be confusing. there are 21 types of amino acids and therefore 21 types of tRNA. but only 20 of them are UNIVERSALLY required (as many organisms do not use selenocysteine)

**Comment by did10** [comment]
Oh makes sense, than sorry for the false alarm
