### ISSUE TITLE
provide latest constructed database 

### ISSUE THREAD

**Issue by kingtom2016** [KIT-IBG-5/mdmcleaner#50]
Thanks you for your good tool.
Directly providing latest constructed database may make this better and easier to access. :)

**Comment by jvollme** [comment]
hi, yes we will definitively set up a way to download ready constructed dbs directly from our servers. This may have to wait until i have had time to optimize the database though...

**Comment by kingtom2016** [comment]
database construction step works well now, so I close the issue.
